### ISSUE TITLE
Plotly rendering issue

### ISSUE THREAD

**Issue by rajatsharma369007** [aurora-nat/disaster_response_pipeline#1]
At line 13 of master.html, you are using an inaccessible API of the Plotly JavaScript data visualization library. Kindly replace the following line
`‌<script src="https://d14fo0winaifog.cloudfront.net/plotly-basic.js"></script>‌
`
with this
`‌<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>‌
`

**Comment by aurora-nat** [comment]
Have updated the API library being used. Thank you.
